name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['13', '14', '15', '16', '17']

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run tests
      run: |
        nix-shell --run "nxpg-${{ matrix.pg-version }} nxpg-build"
        nix-shell --run "nxpg-${{ matrix.pg-version }} nxpg-tmp nxpg-test"
    - if: ${{ failure() }}
      run: cat regression.diffs

  test-on-macos:
    runs-on: macos-13

    strategy:
      matrix:
        pg-version: ['17']

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run tests
      run: |
        nix-shell --run "nxpg-${{ matrix.pg-version }} nxpg-build"
        nix-shell --run "nxpg-${{ matrix.pg-version }} nxpg-tmp nxpg-test"
    - if: ${{ failure() }}
      run: cat regression.diffs


  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pg-version: ['17']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run coverage
        run: |
          nix-shell --run "nxpg-${{ matrix.pg-version }} nxpg-build-cov"
          nix-shell --run "nxpg-${{ matrix.pg-version }} nxpg-tmp nxpg-coverage"

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: ./coverage.info
